# Copyright 2026 UltiHash Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

global:
  image: $CORE_IMAGE
  imagePullPolicy: Always
  imagePullSecrets:
  - registry-credentials
  logLevel: DEBUG
  telemetryExportInterval: 30000
  vroomSecret:
    key: license
    name: vroom
  securityContext:
    capabilities:
      add:
      - SYS_PTRACE
  policies: |
    {
      "Version": "2012-10-17",
      "Statement": {
         "Sid":  "AllowAllForAnybody",
         "Effect": "Allow",
         "Action": "*",
         "Principal": "*",
         "Resource": "*"
       }
    }
    

featureTests:
  nodeSelector:
    purpose: ci
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ci"
      effect: "NoSchedule"

coordinator:
  nodeSelector:
    purpose: ci
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ci"
      effect: "NoSchedule"
  extraEnvs:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: service.name=coordinator

etcd:
  replicaCount: 1
  nodeSelector:
    purpose: ci
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ci"
      effect: "NoSchedule"
  persistence:
    size: 5Gi
    storageClass: local-path

entrypoint:
  replicas: 1
  nodeSelector:
    purpose: ci
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ci"
      effect: "NoSchedule"
  
  ingress:
    enabled: false

deduplicator:
  replicas: 1
  storageClass: local-path
  storageSize: 2Gi
  nodeSelector:
    purpose: ci
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ci"
      effect: "NoSchedule"

database:
  primary:
    nodeSelector:
      purpose: ci
    tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ci"
      effect: "NoSchedule"

    persistence:
      storageClass: local-path
      size: 2Gi

databaseInit:
  image: $DATABASE_INIT_IMAGE
  nodeSelector:
    purpose: ci
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ci"
      effect: "NoSchedule"

storage:
  groups:
    - id: 0
      type: ROUND_ROBIN
      storages: 1
      storageClass: local-path
      size: 5Gi
      mountPath: /var/lib/vrm/storage
      nodeSelector:
        purpose: ci
      tolerations:
        - key: "purpose"
          operator: "Equal"
          value: "ci"
          effect: "NoSchedule"

collector:
  config:
    exporters:
      otlphttp/uptrace:
        endpoint: http://uptrace-backend.uptrace.svc.cluster.local:14318
        headers:
          uptrace-dsn: http://${env:VRM_EXPORTER_TOKEN}@uptrace-backend.uptrace.svc.cluster.local:14318
    receivers:
      kubeletstats: null
      prometheus: null
    service:
      pipelines:
        metrics:
          receivers:
          - otlp
  extraEnvs:
  - name: VRM_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: VRM_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: VRM_EXPORTER_TOKEN 
    valueFrom:
      secretKeyRef:
        name: vroom
        key: token
  nodeSelector:
    purpose: ci
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ci"
      effect: "NoSchedule"
  presets:
    kubeletMetrics:
      enabled: false

exporter:
  enabled: false
