services:
  database:
    image: bitnami/postgresql:16.3.0
    environment:
      POSTGRESQL_PASSWORD: vrm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  etcd:
    image: bitnami/etcd:3.5.12
    environment:
      ALLOW_NONE_AUTHENTICATION: yes

  database-init:
    image: registry.ultihash.io/stable/database-init:1.6.0
    depends_on:
      - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vrm
      SUPER_USER_USERNAME: root
      SUPER_USER_ACCESS_KEY_ID: FANCY-ROOT-KEY
      SUPER_USER_SECRET_KEY: SECRET

      DB_USER: postgres
      DB_HOST: database
      DB_PORT: 5432
      PGPASSWORD: vrm

  coordinator:
    image: registry.ultihash.io/stable/core:1.6.0
    depends_on:
      - etcd
    environment:
      VRM_LICENSE: ${VRM_LICENSE_STRING}
      VRM_LOG_LEVEL: INFO
      VRM_OTEL_ENDPOINT: http://otel:4317
      VRM_TRACES_ENABLED: 1
      VRM_DB_HOSTPORT: database:5432
      VRM_DB_USER: postgres
      VRM_DB_PASS: vrm
      VRM_STORAGE_GROUPS: '[{"id":0,"type":"ROUND_ROBIN","storages":1}]'
    command:
      [
        "/usr/bin/bash",
        "-l",
        "-c",
        "sleep 10 && vrm-cluster --registry etcd:2379 coordinator",
      ]

  storage:
    image: registry.ultihash.io/stable/core:1.6.0
    depends_on:
      - etcd
      - coordinator
    environment:
      VRM_LICENSE: ${VRM_LICENSE_STRING}
      VRM_LOG_LEVEL: INFO
      VRM_OTEL_ENDPOINT: http://otel:4317
      VRM_TRACES_ENABLED: 1
    command:
      [
        "/usr/bin/bash",
        "-l",
        "-c",
        "sleep 10 && vrm-cluster --registry etcd:2379 storage",
      ]

  deduplicator:
    image: registry.ultihash.io/stable/core:1.6.0
    depends_on:
      - etcd
      - storage
      - coordinator
    environment:
      VRM_LICENSE: ${VRM_LICENSE_STRING}
      VRM_LOG_LEVEL: INFO
      VRM_OTEL_ENDPOINT: http://otel:4317
      VRM_TRACES_ENABLED: 1
    command:
      [
        "/usr/bin/bash",
        "-l",
        "-c",
        "sleep 10 && vrm-cluster --registry etcd:2379 deduplicator",
      ]

  entrypoint:
    image: registry.ultihash.io/stable/core:1.6.0
    depends_on:
      - etcd
      - storage
      - deduplicator
      - coordinator
    environment:
      VRM_LICENSE: ${VRM_LICENSE_STRING}
      VRM_LOG_LEVEL: INFO
      VRM_OTEL_ENDPOINT: http://otel:4317
      VRM_TRACES_ENABLED: 1
      VRM_DB_HOSTPORT: database:5432
      VRM_DB_USER: postgres
      VRM_DB_PASS: vrm
    volumes:
      - ./policies.json:/etc/vrm/policies.json
    command:
      [
        "/usr/bin/bash",
        "-l",
        "-c",
        "sleep 15 && vrm-cluster --registry etcd:2379 entrypoint",
      ]
    ports:
      - 8080:8080

  clickhouse:
    image: clickhouse/clickhouse-server:24.7
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - "8123:8123"
      - "9000:9000"

  uptrace:
    image: "uptrace/uptrace:1.7.7"
    restart: on-failure
    volumes:
      - ./uptrace.yml:/etc/uptrace/uptrace.yml
    ports:
      - "14317:14317"
      - "14318:14318"
    depends_on:
      - clickhouse
      - database

  otel:
    image: otel/opentelemetry-collector-contrib:0.118.0
    restart: on-failure
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - uptrace

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
