services:
  database:
    image: bitnami/postgresql:16.3.0
    environment:
      POSTGRESQL_PASSWORD: vrm
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432

  etcd:
    image: bitnami/etcd:3.5.12
    environment:
      ALLOW_NONE_AUTHENTICATION: yes

  database-init:
    image: ghcr.io/ultihash/database-init:gmt
    depends_on:
      - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vrm

      DB_USER: postgres
      DB_HOST: database
      DB_PORT: 5432
      PGPASSWORD: vrm

  storage:
    image: ghcr.io/ultihash/core:gmt-storage-0.6.0
    depends_on:
       - etcd
    environment:
      VRM_LICENSE: '{"version":"v1","customer_id":"Vroom-Test","license_type":"freemium","storage_cap_gib":1048576,"signature":"E5ulpGbxd5F5mHQA8r0RKxK+nFUKc7dAMHHJxgrNsPEJuqhj54F6LfDx0RAY2vFNPvkYmkwNy8LvJIv9UqS1Bw=="}'
      VRM_LOG_LEVEL: DEBUG

  deduplicator:
    image: ghcr.io/ultihash/core:gmt-deduplicator-0.6.0
    depends_on:
      - etcd
      - storage
    environment:
      VRM_LICENSE: '{"version":"v1","customer_id":"Vroom-Test","license_type":"freemium","storage_cap_gib":1048576,"signature":"E5ulpGbxd5F5mHQA8r0RKxK+nFUKc7dAMHHJxgrNsPEJuqhj54F6LfDx0RAY2vFNPvkYmkwNy8LvJIv9UqS1Bw=="}'
      VRM_LOG_LEVEL: DEBUG

  entrypoint:
    image: ghcr.io/ultihash/core:gmt-entrypoint-0.6.0
    depends_on:
      - etcd
      - storage
      - deduplicator
    environment:
      VRM_LICENSE: '{"version":"v1","customer_id":"Vroom-Test","license_type":"freemium","storage_cap_gib":1048576,"signature":"E5ulpGbxd5F5mHQA8r0RKxK+nFUKc7dAMHHJxgrNsPEJuqhj54F6LfDx0RAY2vFNPvkYmkwNy8LvJIv9UqS1Bw=="}'
      VRM_LOG_LEVEL: DEBUG
      VRM_DB_HOSTPORT: database:5432
      VRM_DB_USER: postgres
      VRM_DB_PASS: vrm
    ports:
      - 8080:8080

  stability:
    image: ghcr.io/ultihash/core-stability-test:gmt
    depends_on:
      - storage
      - deduplicator
      - entrypoint
    environment:
      CLUSTER_URL: http://entrypoint:8080
      AWS_ACCESS_KEY_ID: mocked
      AWS_SECRET_ACCESS_KEY: mocked
      AWS_DEFAULT_REGION: eu-central-1h
    volumes:
      - /data/corpora_test/stability-test-mini:/data
