FROM debian:bookworm-slim

RUN apt-get update -y && \
    apt-get install -y postgresql-client

COPY ./tools/database-init/apply_db_schema.sh .

COPY ./data/sql/ /sql

ENTRYPOINT ["/bin/bash"]

CMD ["apply_db_schema.sh"]
