# Copyright 2026 UltiHash Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: performance-tester
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: registry-credentials
  nodeSelector:
    workload-type: tester
    purpose:  performance-testing-large
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"
  containers:
    - name: performance-tester
      image: registry.vroom.io/dev/core-performance-test:latest
      imagePullPolicy: Always
      env:
        - name: TEST_TYPE
          value: $TEST_TYPE
        - name: AMOUNT_GiB
          value: "$AMOUNT_GiB"
        - name: S3_ENDPOINT_URL
          value: $S3_ENDPOINT_URL
        - name: S3_SOURCE_BUCKET
          value: $S3_SOURCE_BUCKET
        - name: S3_DESTINATION_BUCKET
          value: $S3_DESTINATION_BUCKET
        - name: READ_TIMEOUT
          value: "$READ_TIMEOUT"
        - name: JOBS
          value: "$JOBS"
        - name: MULTIPART_CHUNK_SIZE
          value: "$MULTIPART_CHUNK_SIZE"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name:  "${RELEASE_NAME}-super-user-credentials"
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name:  "${RELEASE_NAME}-super-user-credentials"
              key: secret-key
        - name: TEST_NAME
          value: "$TEST_NAME"
        - name: PROM_URL
          value: "$PROM_URL"